name: Main Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - macos-latest
        ocaml-version:
          - 4.14.2  # Latest OCaml 4.x
          - 5.2.1   # Latest OCaml 5.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore opam Cache
        uses: actions/cache@v4
        with:
          path: ~/.opam
          key: ${{ runner.os }}-${{ matrix.ocaml-version }}-opam-folder

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}

      - name: Pin package
        run: opam pin add CS51Utils . --no-action

      - name: Install dependencies
        run: opam install . --deps-only --with-doc --with-test --yes

      - name: Build
        run: opam exec -- dune build --no-buffer

      - name: Test
        run: opam exec -- dune runtest --no-buffer
